services:
  - type: web
    name: estimator
    runtime: node
    rootDir: estimator
    buildCommand: npm ci && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_VERSION
        value: 24